name: CI-SFTP
on:
  push:
    branches: [ master ] 
  workflow_dispatch:
 
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: isemary/Petitfour
        with:
          username: ${{ secrets.VPS_USERNAME }}
          server: ${{ secrets.VPS_DNS_IP }}
          port: ${{ secrets.VPS_PORT }} 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: ${{ secrets.VPS_PROJECT_PATH }}
          # sftp args
          args: '-o ConnectTimeout=5'
